### GET request to example server
GET http://localhost:3000


### Send request with dynamic variables in request's body
POST http://localhost:3000
Content-Type: application/json

{
  "title": "Moscow"
}

### GET request to example server
GET http://localhost:3000/cities


### Send request with dynamic variables in request's body
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email":"dsdas",
  "fullName": "dkfskdfj",
  "password": "233"
}

### GET request with a header
GET http://localhost:3000/api/users
Accept: application/json